// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAndPrintLabel(arg1, arg2) {
  return window['go']['main']['App']['GenerateAndPrintLabel'](arg1, arg2);
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}

export function ParseLogisticsInfo(arg1) {
  return window['go']['main']['App']['ParseLogisticsInfo'](arg1);
}
