// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateAndPrintLabel(arg1:main.LabelData,arg2:boolean):Promise<string>;

export function OpenPDF(arg1:string):Promise<void>;

export function ParseLogisticsInfo(arg1:string):Promise<{[key: string]: any}>;
